# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

"""
FastAPI application for the Maskguard Openenv Environment.

This module restores the scaffold's OpenEnv-compatible server via create_app()
and layers explicit helper endpoints on top for hackathon workflows.
"""

from typing import Any, Dict, List, Optional

from fastapi import Body
from pydantic import BaseModel, Field

try:
    from openenv.core.env_server.http_server import create_app
except Exception as e:  # pragma: no cover
    raise ImportError(
        "openenv is required for the web interface. Install dependencies with '\n    uv sync\n'"
    ) from e

try:
    from ..models import MaskguardOpenenvAction, MaskguardOpenenvObservation
    from .maskguard_openenv_environment import MaskguardOpenenvEnvironment
except ImportError:
    from models import MaskguardOpenenvAction, MaskguardOpenenvObservation
    from server.maskguard_openenv_environment import MaskguardOpenenvEnvironment


app = create_app(
    MaskguardOpenenvEnvironment,
    MaskguardOpenenvAction,
    MaskguardOpenenvObservation,
    env_name="maskguard_openenv",
    max_concurrent_envs=1,
)

singleton_environment = MaskguardOpenenvEnvironment()


class ResetRequest(BaseModel):
    text: Optional[str] = None
    policy_mode: str = Field(default="GDPR")
    task_name: str = Field(default="contact_masking")
    target_entities: List[str] = Field(default_factory=list)


@app.get("/health")
def health_check() -> Dict[str, Any]:
    """Container health endpoint used by Docker and HF Spaces."""
    return {"status": "ok", "environment": "maskguard_openenv"}


@app.get("/state")
def get_state() -> Dict[str, Any]:
    """Return the current singleton environment state."""
    return singleton_environment._env.state()


@app.post("/reset")
def reset_environment(request: ResetRequest = Body(default_factory=ResetRequest)) -> Dict[str, Any]:
    """
    Reset the singleton environment with explicit task configuration.

    This coexists with the OpenEnv routes generated by create_app and keeps the
    requested hackathon-friendly payload shape available at the root endpoint.
    """
    observation = singleton_environment._env.reset(
        text=request.text,
        policy_mode=request.policy_mode,
        task_name=request.task_name,
        target_entities=request.target_entities,
    )
    singleton_environment._state.episode_id = singleton_environment._env.episode_id
    singleton_environment._state.step_count = singleton_environment._env.step_count
    return {
        "observation": observation,
        "reward": 0.0,
        "done": False,
        "info": {"status": "reset"},
    }


@app.post("/submit")
def submit_environment() -> Dict[str, Any]:
    """Submit the singleton environment's current masking result."""
    submission_result = singleton_environment.submit()
    return {
        "observation": singleton_environment._env._build_observation(),
        "reward": submission_result["reward"],
        "done": submission_result["accepted"],
        "info": submission_result,
    }


def main():
    """Entry point for direct execution via uv run or python -m."""
    import uvicorn
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--host", default="0.0.0.0")
    parser.add_argument("--port", type=int, default=8000)
    args = parser.parse_args()
    uvicorn.run(app, host=args.host, port=args.port)


if __name__ == "__main__":
    main()
